@startuml "Object diagram"

object GameStats
object Team
object TeamNotes

object Tournament
object TournamentStage

object Player
object PlayerStats

object SportType

object User

object GameOdds

GameStats o-- Team
GameStats o-- TournamentStage

Team o-- SportType
Team o-- Tournament

Tournament o-- SportType

TournamentStage o-- Tournament

PlayerStats o-- Player
PlayerStats o-- TournamentStage

Player o-- SportType
Player o-- Tournament

GameOdds o-- Tournament
GameOdds o-- TournamentStage
GameOdds o-- Team

TeamNotes o-- Team
TeamNotes o-- User
@enduml
