@startuml "Object diagram"

object GameStats
object Team
object TeamNotes

object Tournament
object TournamentStage

object Player
object PlayerStats

object SportType

object User

object Odds
object Fixtures

object TournamentModel

GameStats "1" o-- "2" Team
GameStats o-- TournamentStage

Team o-- SportType
Team "1" o-- "many" Tournament

Tournament o-- SportType
Tournament *-- TournamentModel

TournamentStage o-- Tournament

PlayerStats o-- Player
PlayerStats o-- TournamentStage

Player o-- SportType
Player o-- Tournament

Fixtures "1" o-- "1" Tournament
Fixtures o-- TournamentStage
Fixtures o-- Team
Fixtures "1" *-- "many" Odds: contains

TeamNotes o-- Team
TeamNotes o-- User
@enduml
